import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Loader from "./Components/Loader/Loader";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<div className="h-screen w-full flex justify-center items-center">
            <div className="w-24 h-24 border-8 border-gray-200 border-t-black rounded-full animate-spin mb-4"></div>
        </div>}>
        <Loader>
        {children}
        </Loader>
        </Suspense>
      </body>
    </html>
  );
}
